### ISSUE TITLE
Scripts folder path requires "/" at the end

### ISSUE THREAD

**Issue by IDDQGM** [Al-Muhandis/ShellRemoteBot#1]
After installation, the bot cannot execute scripts if the Directory path in the [Scripts] section in tgshd.ini does not end with /

После установки бот не может выполнять скрипты если в tgshd.ini путь Directory в секции  [Scripts] не оканчивается на /

**Comment by Al-Muhandis** [comment]
Thanks you for the feedback. Fixed in the last commit
Спасибо за обратную связь. Пофиксил в последнем коммите
