### ISSUE TITLE
Server Shutting Down

### ISSUE THREAD

**Issue by lhost25** [Al-Muhandis/ShellRemoteBot#2]
Hey bro, thanks for this wonderful work.

I think there is an issue with this. After the installation and immediately you enable and start with "systemctl start tgshd" the linux server closed and wont connect again. I have tried this several time with Ubuntu and Debian with the same problem. Once linux server is closed, you wont be able to connect again.

Is it possible i am doing something wrong or what. Attached is screenshot for more explanation.

Thanks @Al-Muhandis 

<img width="813" alt="Screenshot 2023-05-11 at 8 14 07 PM" src="https://github.com/Al-Muhandis/ShellRemoteBot/assets/87344213/b1b2acec-9583-4eca-b50e-d8cdaf51bf68">

**Comment by Al-Muhandis** [comment]
Thanks for feedback. I'll recheck that

**Comment by lhost25** [comment]
> Thanks for feedback. I'll recheck that

is there any solution to the linux server crashing after the installation?

**Comment by Al-Muhandis** [comment]
Maybe I don't understand you that way, but it's not quite correct to call this daemon a server. It works in longpolling mode. It is not server

**Comment by Al-Muhandis** [comment]
So, I rechecked. I didn't find any errors under Ubuntu. 
Let's try to clarify.
1. Do You specify your bot's token in the `/etc/tgshd/tgshd.ini`?
2. Do You have libssl libs? Try to install libs with command `sudo apt install libssl-dev` in Ubuntu terminal

**Comment by Al-Muhandis** [comment]
Ah. I think I understand you. Is your web server shutting down after the daemon is started? Very strange. These are not related services

**Comment by Al-Muhandis** [comment]
But I have this thshd daemon running on my Ubuntu web server as well. There were also no such problems. Maybe some kind of security system works on your web server?

**Comment by lhost25** [comment]
> So, I rechecked. I didn't find any errors under Ubuntu. Let's try to clarify.
> 
> 1. Do You specify your bot's token in the `/etc/tgshd/tgshd.ini`?
> 2. Do You have libssl libs? Try to install libs with command `sudo apt install libssl-dev` in Ubuntu terminal

I will try to install libssl to see what happens next.

I use digital ocean linux 22.04 LTS x64 and 20.04. All linux server closes after installing and starting tgshd and whenever i try connecting back it wont connect to my linux until i reinstall ubuntu.

I will get back to you soon bro and thanks for your assistant.

**Comment by lhost25** [comment]
"Ah. I think I understand you. Is your web server shutting down after the daemon is started? Very strange. These are not related services"

I am still facing the same problem. systemctl enable tgshd and systemctl start tgshd keeps closing my terminal and wont open again.


<img width="1049" alt="Screenshot 2023-05-14 at 7 45 59 AM" src="https://github.com/Al-Muhandis/ShellRemoteBot/assets/87344213/c38aa757-6448-4dac-9a21-7ab37523ddf5">

<img width="1440" alt="Screenshot 2023-05-14 at 7 44 26 AM" src="https://github.com/Al-Muhandis/ShellRemoteBot/assets/87344213/e879b804-a0be-48fa-8f96-56892dbeac10">


> Ah. I think I understand you. Is your web server shutting down after the daemon is started? Very strange. These are not related services

**Comment by Al-Muhandis** [comment]
> I will get back to you soon bro and thanks for your assistant.

Thank you too much for your feedback and help in analyzing this problem. After all, this can happen on other computers. We must try to understand the reasons

**Comment by Al-Muhandis** [comment]
> I am still facing the same problem. systemctl enable tgshd and systemctl start tgshd keeps closing my terminal and wont open again.

Do I understand correctly that it is the entire server that stops working?
Not even connected via SSH? 
Are there any signs of server life being observed through the Digital Ocean website itself? 
Does the bot itself accidentally start working at the same time maybe? 

It's very strange. Can DigitalOcean somehow restrict the work of some daemons in the system?

**Comment by lhost25** [comment]
> > I will get back to you soon bro and thanks for your assistant.
> 
> Thank you too much for your feedback and help in analyzing this problem. After all, this can happen on other computers. We must try to understand the reasons

Yeah and sure.

At first i tried on digital ocean thinking digital ocean might be the problem, now i got a new server from bitlaunch.io with the same problem. I think there is problem with the tgshd starting on linux.

Are you on telegram or where i can provide you a digital ocean linux to try yourself.

Thanks.

**Comment by Al-Muhandis** [comment]
[My telegram](https://t.me/Renat_Suleymanov)

**Comment by Al-Muhandis** [comment]
So, I tried to install it on your web server myself and everything worked. It's not completely clear what happened in the first case, but it worked for me the first time

**Comment by lhost25** [comment]
I made a mistake, it was the WebSSH i used that keep shutting down my server during installation. It eventually work after using putty to run the installation as instructed by @Al-Muhandis.

Thanks to @Al-Muhandis for your time in putting me through. It's smooth running linux command on telegram app.
